
Product.getAll=Select * from ProductDetails
Product.order=update ProductDetails set qty=:qty where productid=:productid
Product.getbyid=select * from ProductDetails where productid=:productid

Order.Insert=Insert Into OrderDetails (orderid,customername,price,status)values(:orderid,:customername,:price,:status)
Order.GetOrder=Select * from OrderDetails
Order.ItemsInsert=Insert into OrderItems (orderid,foodname,qty)  values(:orderid,:foodname,:qty)
Order.ItemsGet=select * from OrderItems where orderid=:orderid;